### ISSUE TITLE
webpack生产环境

### ISSUE THREAD

**Issue by Jabinzou** [codingplayboy/react-blog#4]
您好，我想问一下，就是在正式环境启动项目是直接用express来进行的吗？那么怎么和生产环境区分开来。。。。。

**Comment by emthink** [comment]
@Jabinzou 开发环境使用webpack-dev-server启动本地服务哦，正式环境都是打包出html，js，css部署到服务器的，和webpack已经没有关系了哈。

**Comment by Jabinzou** [comment]
我们使用pm2直接启动的。。。忘记了
